### ISSUE TITLE
Update YouTube player to Exoplayer?

### ISSUE THREAD

**Issue by thepoofy** [thepoofy/the-bakery-public#8]
The library used to show youtube videos has a problem with scrolling in a recyclerview.  See:  https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/848

Investigate Exoplayer. Would this improve playback and UX?

**Comment by thepoofy** [comment]
Consider YouTubePlayerFragment too:  https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayerFragment

**Comment by PierfrancescoSoffritti** [comment]
Hi in case this is still a problem, [see issue #848](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/848), I have updated the example to show a possible way to intercept clicks.
